# Lunes 26 de Febrero 2024

Nota para proyecto:
1. Concepto
2. Propuesta
3. Implementación
4. Resultados
5. Conclusiones / Análisis

In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import numpy.random as rd

In [18]:
A = 2*np.random.randint(9,size=(3,3))/2
F = np.random.rand(3)
print(A)
print(F)
print(A[0,0])

[[1. 4. 8.]
 [7. 6. 8.]
 [8. 4. 1.]]
[0.69644915 0.18750564 0.03022434]
1.0


In [19]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
            print(U)
        return U,G

In [20]:
gauss(A,F)

[[  1.   4.   8.]
 [  0. -22. -48.]
 [  8.   4.   1.]]
[[  1.   4.   8.]
 [  0. -22. -48.]
 [  0. -28. -63.]]


(array([[  1.,   4.,   8.],
        [  0., -22., -48.],
        [  0., -28., -63.]]),
 array([ 0.69644915, -4.68763838, -5.54136882]))

# Martes 27 de Febrero 2024

In [1]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt

In [6]:
def forwsub(L,G):
    n=G.size
    x=np.zeros(n)
    for i in range(n-1):
        x[i]=G[i]/L[i,i]-1/L[i,i]*np.dot(L[i,i-1:],x[i-1:])
    return(x)

In [7]:
def sumu(U,x):
    n=G.size
    x=np.zeros(n)
    for i in reversed(range(n)):
        x[i]=G[i]/U[i,i]-1/U[i,i]*np.dot(U[i,i+1:],x[i+1:])
    return x

In [21]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
            print(U)
        return U,G

In [25]:
A = 2*np.random.randint(9,size=(3,3))/2
F = np.random.rand(3)
print(A)
print(F)

[[5. 3. 4.]
 [8. 8. 6.]
 [3. 4. 8.]]
[0.99922014 0.36847489 0.59910269]


In [26]:
U=gauss(A,F)
U

[[ 5.   3.   4. ]
 [ 0.   3.2 -0.4]
 [ 3.   4.   8. ]]
[[ 5.   3.   4. ]
 [ 0.   3.2 -0.4]
 [ 0.   2.2  5.6]]


(array([[ 5. ,  3. ,  4. ],
        [ 0. ,  3.2, -0.4],
        [ 0. ,  2.2,  5.6]]),
 array([ 9.99220141e-01, -1.23027733e+00, -4.29395732e-04]))