# Lunes 26 de Febrero 2024

Nota para proyecto:
1. Concepto
2. Propuesta
3. Implementación
4. Resultados
5. Conclusiones / Análisis

In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import numpy.random as rd

In [15]:
A = 2*np.random.randint(9,size=(3,3))/2
F = np.random.rand(3)
print(A)
print(F)
print(A[0,0])

[[8. 7. 6.]
 [3. 3. 8.]
 [7. 0. 8.]]
[0.22675853 0.51497718 0.67787724]
8.0


In [24]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
        return U,G

In [25]:
gauss(A,F)

(array([[nan, nan,  6.],
        [nan, nan, nan],
        [nan, nan, nan]]),
 array([nan, nan, nan]))