# Lunes 26 de Febrero 2024

Nota para proyecto:
1. Concepto
2. Propuesta
3. Implementación
4. Resultados
5. Conclusiones / Análisis

In [2]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import numpy.random as rd

In [3]:
A = 2*np.random.randint(9,size=(3,3))/2
F = np.random.rand(3)
print(A)
print(F)
print(A[0,0])

[[3. 8. 1.]
 [4. 8. 1.]
 [3. 8. 4.]]
[0.30334614 0.94339915 0.90316823]
3.0


In [4]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
            print(U)
        return U,G

In [5]:
gauss(A,F)

[[ 3.          8.          1.        ]
 [ 0.         -2.66666667 -0.33333333]
 [ 3.          8.          4.        ]]
[[ 3.          8.          1.        ]
 [ 0.         -2.66666667 -0.33333333]
 [ 0.          0.          3.        ]]


(array([[ 3.        ,  8.        ,  1.        ],
        [ 0.        , -2.66666667, -0.33333333],
        [ 0.        ,  0.        ,  3.        ]]),
 array([0.30334614, 0.53893763, 0.59982209]))