# Lunes 11 Marzo 2024

Ejercicio: Factorizar una matriz, obteniendo la matriz triangular inferior y la matriz triangular superior

In [2]:
import numpy as np
import sympy as sy
import numpy.random as rd

In [3]:
A = 2*np.random.randint(9,size=(3,3))/2
print(A)

[[1. 1. 6.]
 [7. 7. 4.]
 [3. 6. 2.]]


In [ ]:
def doo(A,n):
    low=[[0 for x in range(n)]for y in range(n)]
    up =[[0 for x in range(n)]for y in range(n)]
    for i in range(n):
        for k in range(i,n):
            sum = 0
            for j in range(i):
                sum += (low[i][j]*up[j][k])
            up[i][k]=A[i][k]-sum
        for k in range(i,n):
            if(i==k):
                low[i][i]=1
            else:
                sum = 0
                for j in range(i):
                    sum += (low[k][j]*up[j][i])
                low[k][i]=int((mat[k][i]-sum)/up[i][i])